# Generated by Django 6.0.4 on 2026-04-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.IntegerField()),
                ('english', models.IntegerField()),
                ('gujarati', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('total', models.IntegerField()),
                ('per', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TO_DO.students')),
            ],
        ),
    ]
